//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubraDoze.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogada
    {
        public int Id { get; set; }
        public string Operacoes { get; set; }
        public string Time { get; set; }
        public Nullable<System.DateTime> DataRegistro { get; set; }
        public int IdPartida { get; set; }
        public Nullable<int> Tempo { get; set; }
        public Nullable<bool> Acertou { get; set; }
    
        public virtual Partida Partida { get; set; }
    }
}
